package gui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Conector;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.commons.net.ftp.FTPReply;

public class Noticias extends javax.swing.JFrame {
// Se instancia una conexion de la clase conecta

    Conector con = new Conector();
    // se asigna la conexion a la base de datos con la variable cn
    Connection cn = con.conecta();

    DefaultTableModel modelo;

    //direccion de la imagen
    File file = null;

    public Noticias() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicio();
        mostrarTabla();
        txtId.setVisible(false);
        
    }

    private void inicio() {
        txtTags.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtIntro.setEnabled(false);
        txtTexto.setEnabled(false);
        txtImagen.setEnabled(false);
        btAgregar.setEnabled(false);
    }

    private void nuevo() {
        txtTags.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtIntro.setEnabled(true);
        txtTexto.setEnabled(true);
        txtImagen.setEnabled(true);
        btAgregar.setEnabled(true);
    }

    private void fecha() {
        SimpleDateFormat formateador = new SimpleDateFormat("EEEEEEEEE dd 'de'  MMMMM 'de' yyyy");
        Calendar cal = Calendar.getInstance();
        cal.setTimeZone(TimeZone.getDefault());
        System.out.println(formateador.format(new Date()));
        txtFecha.setText(formateador.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIntro = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtTags = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        btNueva = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jdInicio = new com.toedter.calendar.JDateChooser();
        jdFinal = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscaTags = new javax.swing.JTextField();
        txtBuscaTexto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtImagen = new javax.swing.JTextField();
        btAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        imgNoticia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Publicacion"));

        jLabel1.setText("Fecha:");

        txtFecha.setText("_");

        jLabel2.setText("Titulo de la nota");

        jLabel3.setText("Introduccion:");

        txtIntro.setColumns(20);
        txtIntro.setLineWrap(true);
        txtIntro.setRows(5);
        jScrollPane1.setViewportView(txtIntro);

        jLabel4.setText("Nota Completa");

        txtTexto.setColumns(20);
        txtTexto.setLineWrap(true);
        txtTexto.setRows(5);
        jScrollPane2.setViewportView(txtTexto);

        jLabel5.setText("Tags");

        txtId.setText("_");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha))
                            .addComponent(txtId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTags))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha)
                    .addComponent(jLabel5)
                    .addComponent(txtTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btNueva.setText("Nueva");
        btNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNueva)
                .addGap(18, 18, 18)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btEliminar)
                .addGap(18, 18, 18)
                .addComponent(btSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        jLabel8.setText("Entre Fechas:");

        jLabel9.setText("Y");

        jLabel10.setText("Tags");

        jLabel11.setText("Texto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jdInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscaTags, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBuscaTexto))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscaTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBuscaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel9))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));

        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        jLabel6.setText("Vista previa");

        imgNoticia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/noticia.png"))); // NOI18N
        imgNoticia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btAgregar))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImagen)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAgregar)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(imgNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void mostrarTabla() {
        String[] cabecera = {"Id", "Fecha", "Titulo"};
        String[] registros = new String[7];
        String sql = "SELECT * FROM noticias ORDER BY id DESC";
        //establecemos los anchos en pixeles de las columnas
        int[] anchos = {0, 250, 600};

        modelo = new DefaultTableModel(null, cabecera);
        try {

            Statement table;
            table = cn.createStatement();
            ResultSet rs = table.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("fecha");
                registros[2] = rs.getString("titulo");

                modelo.addRow(registros);

            }
            tabla.setModel(modelo);
            for (int i = 0; i < cabecera.length; i++) {
                tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tabla.setFont(new java.awt.Font("Tahoma", 0, 12));
            }
            tabla.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla.getColumnModel().getColumn(0).setMinWidth(0);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }
    }
    private void btNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaActionPerformed
        if (btNueva.getText().equals("Nueva")) {
            nuevo();
            btBuscar.setEnabled(false);
            btEditar.setEnabled(false);
            btEliminar.setEnabled(false);
            btNueva.setText("Agregar");
            fecha();
        } else {
            if (txtTags.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Te falta colocar Tags");
                txtTags.requestFocus();
            } else if (txtTitulo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Te falta colocar Titulo");
                txtTitulo.requestFocus();
            } else if (txtIntro.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Te falta la cabecera de la noticia");
                txtIntro.requestFocus();
            } else if (txtTexto.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Te falta colocar la Noticia");
                txtTexto.requestFocus();
            } else if (txtImagen.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Te falta Agregar imagen");
                txtImagen.requestFocus();
            } else {
                String fecha = txtFecha.getText();
                String tags = txtTags.getText();
                String titulo = txtTitulo.getText();
                String intro = txtIntro.getText();
                String texto = txtTexto.getText();
                String imagen = txtImagen.getText();
                try {
                    String sql = "INSERT INTO noticias (fecha,tags,titulo,intro,texto,imagen) "
                            + "VALUES (?,?,?,?,?,?)";
                    PreparedStatement ps = cn.prepareStatement(sql);
                    ps.setString(1, fecha);
                    ps.setString(2, tags);
                    ps.setString(3, titulo);
                    ps.setString(4, intro);
                    ps.setString(5, texto);
                    ps.setString(6, imagen);
                    ps.executeUpdate();
                    btNueva.setText("Nueva");
                    mostrarTabla();
                    System.out.println("integrado en la bd");
                    // proceso de la imagen
                    procesaImagen();
                    System.out.println("imagen procesada");
                    //Manda Imagen por ftp
                    subeImagen();
                    System.out.println("imagen subida");
                    //actualiza BD
                    String id=tabla.getValueAt(0,0).toString();
                    
                    //actualizamos la bd
                    Statement st;
                    st=cn.createStatement();
                    st.executeUpdate("UPDATE noticias set imagen='"+id+".png' WHERE id='"+id+"'");
                    System.out.println("base de datos actualizada");
                    //Limpiamos
                    JOptionPane.showMessageDialog(this, "Noticia se ha publicado correctamente");
                    Noticias frm=new Noticias();
                    frm.setVisible(true);
                    this.dispose();
                } catch (SQLException e) {
                    Logger.getLogger(Noticias.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }
    }//GEN-LAST:event_btNuevaActionPerformed
    private void procesaImagen() {
        try {
            BufferedImage img = ImageIO.read(new File(txtImagen.getText()));

            Image image = img.getScaledInstance(360, 230, Image.SCALE_SMOOTH);
            BufferedImage buffered = new BufferedImage(360, 230, Image.SCALE_SMOOTH);
            buffered.getGraphics().drawImage(image, 0, 0, null);
            File outputfile = new File(tabla.getValueAt(0, 0).toString() + ".png");
            ImageIO.write(buffered, "png", outputfile);
        } catch (IOException e) {

        }
    }

    private void subeImagen() {
        FTPClient client = new FTPClient();
        try {
            client.connect("maorivera.com");
            boolean login = client.login("cobat@maorivera.com", "Barbara2401");
            if (login) {
                System.out.println("Iniciando sesión Satisfactoriamente");
                int replay = client.getReplyCode();
                if (FTPReply.isPositiveCompletion(replay)) {
                    File file = new File(tabla.getValueAt(0,0).toString()+".png");
                    FileInputStream input = new FileInputStream(file);
                    client.setFileType(FTP.BINARY_FILE_TYPE);
                    client.enterLocalPassiveMode();
                    System.out.println("Subió satisfactoriamente el archivo");
                    if (!client.storeFile(file.getName(), input)) {
                        System.out.println("Subida fallida!");
                    }
                    input.close();
                }
// Cuando cierras sesión el método logout regresa "true".
                boolean logout = client.logout();
                if (logout) {
                    System.out.println("Salir del servidor FTP");
                }
            } else {
                System.out.println("Falló inciar sesión");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
// Cierra la conexión al servidor FTP
                client.disconnect();
            } catch (IOException e) {
                e.printStackTrace();
            }

        }
    }
    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        //agregar imagen

        // iniciamos de nuevo
        JFileChooser seleccion = new JFileChooser();
        //Titulo que llevara la ventana
        seleccion.setDialogTitle("Selecciona la imagen de la noticia");
        seleccion.setAcceptAllFileFilterUsed(false);
        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.JPG", "jpg", "*.PNG", "png");

        //Le indicamos el filtro
        seleccion.setFileFilter(filtro);
        int opcion = seleccion.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {

            file = seleccion.getSelectedFile();
            txtImagen.setText(file.toString());
            ImageIcon icon = new ImageIcon(file.getPath());
            Image conversion = icon.getImage();
            Image escala = conversion.getScaledInstance(240, 138, Image.SCALE_SMOOTH);
            ImageIcon calzado = new ImageIcon(escala);
            imgNoticia.setIcon(calzado);

        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        //editamos la nota
        if (btEditar.getText().equals("Editar")){
        int fila=tabla.getSelectedRow();
       if (fila<0){
                       JOptionPane.showMessageDialog(this, "Selecciona un elemento de la tabla");
                 
                            }
       if (fila>=0){
          btEditar.setText("Actualizar");
          btNueva.setEnabled(false);
          btAgregar.setEnabled(false);
          btEliminar.setEnabled(false);
          
          txtTags.setEnabled(true);
          txtTitulo.setEnabled(true);
          txtIntro.setEnabled(true);
          txtTexto.setEnabled(true);
          String buscarNoticia;
          buscarNoticia = tabla.getValueAt(fila,0).toString();
          
          try{
              Statement buscar=cn.createStatement();
              String sql=("SELECT * FROM noticias WHERE id='"+buscarNoticia+"'");
              ResultSet resultado= buscar.executeQuery(sql);
              
              while (resultado.next()){
                 txtId.setText(resultado.getString("id")); 
                 txtTags.setText(resultado.getString("tags")); 
                 txtFecha.setText(resultado.getString("fecha"));
                 txtTitulo.setText(resultado.getString("titulo"));
                 txtIntro.setText(resultado.getString("intro"));
                 txtTexto.setText(resultado.getString("texto"));
                 
                 
                 
              }
          } catch (SQLException ex) {
               Logger.getLogger(Noticias.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       }else if (btEditar.getText().equals("Actualizar")){
           
           String actualizar="update noticias set tags=?,titulo=?,intro=?,texto=? WHERE id='"+txtId.getText()+"'";
        
        try {
            PreparedStatement ps;
            ps = cn.prepareStatement(actualizar);
            
            ps.setString(1,txtTags.getText());
            ps.setString(2,txtTitulo.getText());
            ps.setString(3,txtIntro.getText());
            ps.setString(4,txtTexto.getText());
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "La noticia se ha actualizado correctamente");
            //ya que se grabo en la base de datos pasamos a dejar todo de nuevo para un nueva noticia
            btNueva.setEnabled(true);
            btEditar.setEnabled(true);
            btEditar.setText("Editar");
            btEliminar.setEnabled(true);
            btSalir.setEnabled(true);
            btBuscar.setEnabled(true);
            
            txtTags.setText("");
            txtFecha.setText("");
            txtTitulo.setText("");
            txtIntro.setText("");
            txtTexto.setText("");
            
            mostrarTabla();
            
            
            
            // creamos la imagen de default del calzado
            ImageIcon imagenDefault = new ImageIcon(getClass().getResource("/imagenes/noticia.png"));
            imgNoticia.setIcon(imagenDefault);
        } catch (SQLException ex) {
            Logger.getLogger(Noticias.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Hay un problema con la BD, la noticia no se ha actualizado");
        }
          
       }
        
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
         //Borrado de una noticia
        
        int fila = tabla.getSelectedRow();
        
       if (fila>=0){
           String BuscarProducto;
           BuscarProducto = tabla.getValueAt(fila, 0).toString();
           
           try{
            Statement buscar = cn.createStatement();
            ResultSet resultado = buscar.executeQuery( "SELECT * FROM noticias WHERE id='"+BuscarProducto+"'" );
            while ( resultado.next() ) {
              int respuesta=JOptionPane.showConfirmDialog(this, "Se va a eliminar la Siguiente nota\nfecha:"
               +tabla.getValueAt(fila, 1).toString()+"\nTitulo:"
               +tabla.getValueAt(fila, 2).toString(), "Confirmacion", 2);
              
              
       //verificamos que informacion se va a eliminar 
        if (respuesta==0){
            try{
            String sql="DELETE FROM noticias WHERE id="+tabla.getValueAt(fila,0);
            Statement st;
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Nota Eliminada");
            mostrarTabla();
            st.close();
            
            
        }
        catch (Exception ex){
          JOptionPane.showMessageDialog(null,"no se elimino el elemento");
        }
                
            }
            }
            }
            catch (SQLException ex){
           System.out.println ("Sin poder ejecutar el query a la tabla");
       }
           }
       
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        //buscamos noticias
        
    }//GEN-LAST:event_btBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Noticias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Noticias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btNueva;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel imgNoticia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdFinal;
    private com.toedter.calendar.JDateChooser jdInicio;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscaTags;
    private javax.swing.JTextField txtBuscaTexto;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextArea txtIntro;
    private javax.swing.JTextField txtTags;
    private javax.swing.JTextArea txtTexto;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
